const videos = [
  { id: 1, title: 'The quiet art of paying attention', creator: 'Ava Chen', category: 'Documentary', duration: '08:42', views: '1.2M views', age: '2 days ago', color: '0f2027', video: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', description: 'A tiny film about slowing down and noticing what is already around you.' },
  { id: 2, title: 'A field guide to better mornings', creator: 'Milo Studio', category: 'Lifestyle', duration: '12:18', views: '842K views', age: '5 days ago', color: '3b1f2b', video: 'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4', description: 'Small rituals, good light, and a little less rushing.' },
  { id: 3, title: 'Building a tiny home in the woods', creator: 'Northbound', category: 'Adventure', duration: '18:04', views: '2.4M views', age: '1 week ago', color: '183c35', video: 'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4', description: 'Follow along as a handmade shelter takes shape among the trees.' },
  { id: 4, title: 'Why everything feels so loud online', creator: 'The Context', category: 'Ideas', duration: '09:55', views: '634K views', age: '2 weeks ago', color: '32254a', video: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', description: 'An illustrated essay on attention, algorithms, and finding your signal.' },
  { id: 5, title: 'Cooking with three ingredients', creator: 'Sora Kitchen', category: 'Food', duration: '06:27', views: '1.8M views', age: '3 weeks ago', color: '55351d', video: 'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4', description: 'Three comforting recipes for when the fridge looks empty.' },
  { id: 6, title: 'The future is beautifully weird', creator: 'Soft Focus', category: 'Culture', duration: '14:31', views: '927K views', age: '1 month ago', color: '17385a', video: 'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4', description: 'A hopeful tour through the strange and wonderful things being made today.' }
];
const categories = ['All videos', 'Documentary', 'Lifestyle', 'Adventure', 'Ideas', 'Food', 'Culture'];
let activeCategory = 'All videos';
const grid = document.querySelector('#video-grid');
const chips = document.querySelector('#chips');
const empty = document.querySelector('#empty-state');
const searchInput = document.querySelector('#search-input');

function thumbnail(video) { return `https://images.unsplash.com/photo-149-${video.id === 1 ? '7366811353-6870744d04b2' : video.id === 2 ? '4624720119-7f2e5c4f4e2' : video.id === 3 ? '1449157291145-7d8f5a7d6b4a' : video.id === 4 ? '1516321318423-f06f85e504b3' : video.id === 5 ? '1542838132-92c53300491e' : '1500530855697-b586d89ba3ee'}?auto=format&fit=crop&w=900&q=80`; }
function renderCategories() { chips.innerHTML = categories.map(c => `<button class="chip ${c === activeCategory ? 'active' : ''}" data-category="${c}">${c}</button>`).join(''); document.querySelector('#side-categories').innerHTML = categories.slice(1, 5).map(c => `<a class="nav-link" href="#" data-category="${c}"><span>•</span> ${c}</a>`).join(''); }
function renderVideos() { const query = searchInput.value.toLowerCase().trim(); const filtered = videos.filter(v => (activeCategory === 'All videos' || v.category === activeCategory) && [v.title, v.creator, v.category].some(x => x.toLowerCase().includes(query))); grid.innerHTML = filtered.map(v => `<article class="video-card" data-id="${v.id}"><div class="thumbnail"><img src="${thumbnail(v)}" alt="${v.title}" loading="lazy"><div class="play-overlay"><span>▶</span></div><span class="duration">${v.duration}</span></div><div class="video-details"><h3 class="video-title">${v.title}</h3><p class="meta">${v.creator}<span class="dot">•</span>${v.views}<span class="dot">•</span>${v.age}</p></div></article>`).join(''); empty.classList.toggle('hidden', filtered.length > 0); }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
function openVideo(video) { const modal = document.querySelector('#watch-modal'); const player = document.querySelector('#player'); document.querySelector('#player-title').textContent = video.title; document.querySelector('#player-category').textContent = `${video.category}  ·  ${video.creator}`; document.querySelector('#player-description').textContent = video.description; player.src = video.video; modal.classList.remove('hidden'); document.body.style.overflow = 'hidden'; player.play().catch(() => {}); }
function closeVideo() { const modal = document.querySelector('#watch-modal'); const player = document.querySelector('#player'); player.pause(); player.removeAttribute('src'); player.load(); modal.classList.add('hidden'); document.body.style.overflow = ''; }
renderCategories(); renderVideos();
chips.addEventListener('click', e => { if (!e.target.matches('[data-category]')) return; activeCategory = e.target.dataset.category; renderCategories(); renderVideos(); });
document.querySelector('#side-categories').addEventListener('click', e => { const link = e.target.closest('[data-category]'); if (!link) return; e.preventDefault(); activeCategory = link.dataset.category; renderCategories(); renderVideos(); });
grid.addEventListener('click', e => { const card = e.target.closest('[data-id]'); if (card) openVideo(videos.find(v => v.id === Number(card.dataset.id))); });
searchInput.addEventListener('input', renderVideos); document.querySelector('#search-form').addEventListener('submit', e => { e.preventDefault(); renderVideos(); });
document.querySelector('#clear-filter').addEventListener('click', () => { activeCategory = 'All videos'; searchInput.value = ''; renderCategories(); renderVideos(); });
document.querySelector('#close-modal').addEventListener('click', closeVideo); document.querySelector('.modal-backdrop').addEventListener('click', closeVideo); document.addEventListener('keydown', e => { if (e.key === 'Escape') closeVideo(); });
document.querySelector('#like-button').addEventListener('click', e => { e.currentTarget.classList.toggle('liked'); e.currentTarget.innerHTML = e.currentTarget.classList.contains('liked') ? '♥ <span>Liked</span>' : '♡ <span>Like</span>'; });
document.querySelector('#theme-button').addEventListener('click', () => { document.body.classList.toggle('light'); });
document.querySelector('#upload-button').addEventListener('click', () => document.querySelector('#file-input').click());
document.querySelector('#file-input').addEventListener('change', e => { const file = e.target.files[0]; if (!file) return; const newVideo = { id: Date.now(), title: file.name.replace(/\.[^/.]+$/, ''), creator: 'You', category: 'Your uploads', duration: 'LOCAL', views: 'Just now', age: '', color: '222', video: URL.createObjectURL(file), description: 'A video from your device.' }; videos.unshift(newVideo); activeCategory = 'All videos'; renderCategories(); renderVideos(); showToast('Video added to your library'); });
